[workspace]
members = ["saguaro", "saguaro_cli", "saguaro_web"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["Matthew Daly"]
license = "GPL-3.0-only"
repository = "https://github.com/matthewd673/saguaro"
description = "Saguaro is a SAT solver"
