[package]
name = "saguaro_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
saguaro = { path = "../saguaro" }